spring:
  application:
    # O Spring vai buscar a variável APP_NAME. Se não achar, usa 'ms-generico'
    name: ${APP_NAME:ms-generico}
  datasource:
    # O Spring vai buscar essas variáveis que o Docker Compose injetou
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  # O Spring vai buscar a variável SERVER_PORT. Se não achar, usa 8080
  port: ${SERVER_PORT:8080}

jwt:
  # Aqui ele puxa a sua chave segura
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    com.autobots: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"